version: '3.8'

networks:
  kong-network:
    driver: bridge

volumes:
  kong-vol:
  konga-postgresql:

services:
  kong-database:
    image: postgres:9.6
    container_name: kong-database
    networks:
      - kong-network
    environment:
      POSTGRES_USER: kong
      POSTGRES_DB: kong
      POSTGRES_PASSWORD: kong
    ports:
      - "5432:5432"
    volumes:
      - kong-vol:/var/lib/postgresql/data

  kong-migrations:
    image: kong:latest
    networks:
      - kong-network
    depends_on:
      - kong-database
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: kong-database
      KONG_PG_PASSWORD: kong
    command: kong migrations bootstrap
    restart: on-failure

  kong:
    image: kong:latest
    container_name: kong
    networks:
      - kong-network
    depends_on:
      - kong-database
      - kong-migrations
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: kong-database
      KONG_PG_PASSWORD: kong
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: 0.0.0.0:8001, 0.0.0.0:8444 ssl
    ports:
      - "8000:8000"
      - "8443:8443"
      - "8001:8001"
      - "8444:8444"
    restart: always

  konga-database:
    image: postgres:9.6
    container_name: konga-database
    networks:
      - kong-network
    environment:
      POSTGRES_USER: kong
      POSTGRES_DB: konga
      POSTGRES_PASSWORD: kong
    ports:
      - "5433:5432"
    volumes:
      - konga-postgresql:/var/lib/postgresql/data

  konga-prepare:
    image: pantsel/konga
    networks:
      - kong-network
    depends_on:
      - konga-database
    command: -c prepare -a postgres -u postgresql://kong:kong@konga-database:5432/konga
    restart: on-failure

  konga:
    image: pantsel/konga
    container_name: konga
    networks:
      - kong-network
    depends_on:
      - konga-database
      - konga-prepare
    environment:
      DB_ADAPTER: postgres
      DB_HOST: konga-database
      DB_USER: kong
      DB_PASSWORD: kong
      DB_DATABASE: konga
      KONGA_HOOK_TIMEOUT: 120000
      NODE_ENV: production
    ports:
      - "1337:1337"
    restart: always
